### ISSUE TITLE
Enable splitting of state

### ISSUE THREAD

**Issue by demeyerthom** [mach-composer/mach-composer-cli#285]
On big projects our deployments have been slowing down significantly. This is caused by mach-composer managing all state in a single state file. This means that all state needs to be checked before deployment, even if it is state belonging to components that have nothing to do with the component actually merged. 

To alleviate this problem, and be able to trigger more granular deployments, we want to enable mach composer to split state along predefined lines. This would allow for more selective deployments, speeding up CI/CD pipelines. An additional advantage is that it makes the overall platform more stable, as a faulty deployment will not cause the whole state of the project to be faulty, but only the affected component.

The proposed structure currently is to split the state according to the following lines:
- Main (containing global state) => This is currently not used
- Site (containing site-wide state) => here we have some legacy elements, like the commercetools settings
- Site Component (containing component state) => this is the major building block that makes up the project as a whole

To allow for this several issues need to be tackled:
- [x] #258
- [x] #287
- [x] Add remote_state references where one component relies on another
- [x] Executing state changes in dependency order
- [x] #326
- [x] #336
- [x] #339
- [x] fix lockfile handling
- [ ] #338
- [ ] Add tests
- [ ] Update docs

**Comment by demeyerthom** [comment]
We might also want to add additional structural elements to group components together, so we can also create stacks along for example team lines. This would further insulate teams from effects of state changes they are not involved in
